// ------ Scale Adjustment Window - Replace -------------------------------------------------------------------------------------------------------------------------------------------

global string $MRS_FlexiChainDouble_ScaleAdjustmentUI_WorkspaceControl = "MRS_FlexiChainDouble_ScaleAdjustmentUI_WorkspaceControl";
global string $MRS_FlexiChainDouble_ScaleAjustmentUI = "MRS_FlexiChainDouble_ScaleAjustmentUI";

global proc MRS_FlexiChainDouble_scaleAdjustmentUIReplace(string $nodeManipPlugName)
{
	// Global values
	global string $MRS_FlexiChainDouble_ScaleAdjustmentUI_WorkspaceControl;
	global string $MRS_FlexiChainDouble_ScaleAjustmentUI;
	
	if (`workspaceControl -q -exists $MRS_FlexiChainDouble_ScaleAdjustmentUI_WorkspaceControl` && `workspaceControl -q -visible $MRS_FlexiChainDouble_ScaleAdjustmentUI_WorkspaceControl`)
	{
		if (`window -q -exists $MRS_FlexiChainDouble_ScaleAjustmentUI`)
		{
			if (`window -q -title $MRS_FlexiChainDouble_ScaleAjustmentUI` == ($nodeManipPlugName + ".scaleAdjustmentRamp"))
				return;
		}
		
		int $isCollapsed = `workspaceControl -q -collapse $MRS_FlexiChainDouble_ScaleAdjustmentUI_WorkspaceControl`;
		MRS_FlexiChainDouble_scaleAdjustmentUINew $nodeManipPlugName;
		workspaceControl -e -collapse $isCollapsed $MRS_FlexiChainDouble_ScaleAdjustmentUI_WorkspaceControl;
	}
}