// ------ Twist Adjustment Window - Replace -------------------------------------------------------------------------------------------------------------------------------------------

global string $MRS_FlexiChainTriple_TwistAdjustmentUI_WorkspaceControl = "MRS_FlexiChainTriple_TwistAdjustmentUI_WorkspaceControl";
global string $MRS_FlexiChainTriple_TwistAjustmentUI = "MRS_FlexiChainTriple_TwistAjustmentUI";

global proc MRS_FlexiChainTriple_twistAdjustmentUIReplace(string $nodeManipPlugName)
{
	// Global values
	global string $MRS_FlexiChainTriple_TwistAdjustmentUI_WorkspaceControl;
	global string $MRS_FlexiChainTriple_TwistAjustmentUI;
	
	if (`workspaceControl -q -exists $MRS_FlexiChainTriple_TwistAdjustmentUI_WorkspaceControl` && `workspaceControl -q -visible $MRS_FlexiChainTriple_TwistAdjustmentUI_WorkspaceControl`)
	{
		if (`window -q -exists $MRS_FlexiChainTriple_TwistAjustmentUI`)
		{
			if (`window -q -title $MRS_FlexiChainTriple_TwistAjustmentUI` == ($nodeManipPlugName + ".twistAdjustmentRamp"))
				return;
		}
		
		int $isCollapsed = `workspaceControl -q -collapse $MRS_FlexiChainTriple_TwistAdjustmentUI_WorkspaceControl`;
		MRS_FlexiChainTriple_twistAdjustmentUINew $nodeManipPlugName;
		workspaceControl -e -collapse $isCollapsed $MRS_FlexiChainTriple_TwistAdjustmentUI_WorkspaceControl;
	}
}