// ------ Scale Adjustment Window - Replace -------------------------------------------------------------------------------------------------------------------------------------------

global string $MRS_FlexiChainSingle_ScaleAdjustmentUI_WorkspaceControl = "MRS_FlexiChainSingle_ScaleAdjustmentUI_WorkspaceControl";
global string $MRS_FlexiChainSingle_ScaleAjustmentUI = "MRS_FlexiChainSingle_ScaleAjustmentUI";

global proc MRS_FlexiChainSingle_scaleAdjustmentUIReplace(string $nodeManipPlugName)
{
	// Global values
	global string $MRS_FlexiChainSingle_ScaleAdjustmentUI_WorkspaceControl;
	global string $MRS_FlexiChainSingle_ScaleAjustmentUI;
	
	if (`workspaceControl -q -exists $MRS_FlexiChainSingle_ScaleAdjustmentUI_WorkspaceControl` && `workspaceControl -q -visible $MRS_FlexiChainSingle_ScaleAdjustmentUI_WorkspaceControl`)
	{
		if (`window -q -exists $MRS_FlexiChainSingle_ScaleAjustmentUI`)
		{
			if (`window -q -title $MRS_FlexiChainSingle_ScaleAjustmentUI` == ($nodeManipPlugName + ".scaleAdjustmentRamp"))
				return;
		}
		
		int $isCollapsed = `workspaceControl -q -collapse $MRS_FlexiChainSingle_ScaleAdjustmentUI_WorkspaceControl`;
		MRS_FlexiChainSingle_scaleAdjustmentUINew $nodeManipPlugName;
		workspaceControl -e -collapse $isCollapsed $MRS_FlexiChainSingle_ScaleAdjustmentUI_WorkspaceControl;
	}
}